In [2]:
import numpy as np

In [8]:
my_1d_array = np.array([1, 2, 3, 4, 5])
print(my_1d_array)

[1 2 3 4 5]


In [9]:
my_1d_array.shape

(5,)

In [10]:
my_1d_array.ndim

1

In [11]:
my_1d_array.dtype

dtype('int64')

In [12]:
my_2d_array = np.array([[1, 2, 3], [3, 5, 6]])
print(my_2d_array)

[[1 2 3]
 [3 5 6]]


In [13]:
my_2d_array.shape

(2, 3)

In [14]:
my_2d_array.ndim

2

In [27]:
my_3d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(my_3d_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
my_3d_array[0][1][1] = 4

In [44]:
my_3d_array[1][1][1] = 4

In [45]:
my_3d_array

array([[[ 1,  2,  3],
        [ 4,  4,  6]],

       [[ 7,  8,  9],
        [10,  4, 12]]])

In [15]:
print(my_3d_array.ndim)

3


In [7]:
print(my_3d_array.shape)

(2, 2, 3)


In [16]:
my_1d_array = np.array([1, 2, 3, 4, 5])
my_1d_array[0] = 8
print(my_1d_array)

[8 2 3 4 5]


In [17]:
my_2d_array = np.array([[1, 2, 3], [3, 5, 6]])
my_2d_array[0][1] = 10
print(my_2d_array)

[[ 1 10  3]
 [ 3  5  6]]


In [18]:
#zeros
arr_zeros = np.zeros((3, 4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#ones
arr_ones = np.ones((2, 2))
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [20]:
#full
arr_full = np.full((5, 5), 20, dtype=int)
print(arr_full)

[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [32]:
# arrange
arr_arange = np.arange(1, 5, 1)

In [33]:
print(arr_arange)

[1 2 3 4]


In [34]:
#eye
arr_eye = np.eye(4)


In [35]:
print(arr_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
#random
arr_random = np.random.random((3, 3))
print(arr_random)

[[0.57476642 0.24698616 0.94535029]
 [0.22837293 0.25766772 0.56951056]
 [0.27188859 0.52803306 0.00578816]]


In [37]:
arr_random = np.random.randint(1, 5, (3, 3))
print(arr_random)

[[2 3 3]
 [4 1 1]
 [3 2 3]]


In [46]:
#clip
my_arr = np.array([1, 5, 8, 10, 3, 6])
print(my_arr)

[ 1  5  8 10  3  6]


In [47]:
my_arr_clip = np.clip(my_arr, a_min=3, a_max = 8)
print(my_arr_clip)

[3 5 8 8 3 6]


In [48]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_cc = np.concatenate((arr_1, arr_2))
print(arr_cc)

[1 2 3 4 5 6]


In [50]:
my_arr = np.array([1, 2, 3, 4, 5])
my_arr.shape

(5,)

In [52]:
my_arr

array([1, 2, 3, 4, 5])

In [59]:
arr_new = my_arr[:, np.newaxis, np.newaxis, np.newaxis]
print(arr_new)
print(arr_new.shape)

[[[[1]]]


 [[[2]]]


 [[[3]]]


 [[[4]]]


 [[[5]]]]
(5, 1, 1, 1)


In [56]:
arr_new = my_arr[np.newaxis, :]
print(arr_new)
print(arr_new.shape)

[[1 2 3 4 5]]
(1, 5)


In [60]:
def compare(arr1, arr2):
  if arr1 < arr2:
    return 1
  else:
    return 0

compare(2, 3)

1

In [61]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 0, 1, 4])

compare(arr1, arr2)

ValueError: ignored

In [62]:
#vectorize
vectorize_compare = np.vectorize(compare)

In [63]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 0, 1, 4])
vectorize_compare(arr1, arr2)

array([1, 1, 0, 0, 0])

In [64]:
#circle area
def caculate_circle_area(radius):
  return 3.14*radius**2



In [65]:
caculate_circle_area(3)

28.26

In [66]:
vectorize_caculate_circle_area = np.vectorize(caculate_circle_area)

In [67]:
radius_arr = np.array([1, 2, 3, 4])
vectorize_caculate_circle_area(radius_arr)

array([ 3.14, 12.56, 28.26, 50.24])

In [68]:
my_arr = np.array([[1, 2, 3,], [4, 5, 6]])

In [72]:
new_arr = np.where(my_arr <3, 0, my_arr)

In [73]:
print(new_arr)

[[0 0 3]
 [4 5 6]]


In [77]:
#flatten
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_flatten = arr.flatten()
arr_flatten

array([1, 2, 3, 4, 5, 6])

In [80]:
#reshape
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(1, 1, 1, 2, 3)
print(new_arr)

[[[[[1 2 3]
    [4 5 6]]]]]


In [81]:
#reshape
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(1, 1, 1, 2, 3)
print(new_arr)

[[[[[1 2 3]
    [4 5 6]]]]]


In [82]:
new_arr(6, )

TypeError: ignored