In [1]:
import numpy as np

# Creating Arrays

## Bài tập 1: Bạn hãy xây dựng chương trình thực hiện:
    
* Tạo một mảng 1D từ danh sách [1, 2, 3, 4, 5].

* Tạo một mảng 2D kích thước 2x3 từ danh sách [[1, 2, 3], [4, 5, 6]].

* Tạo một mảng 3D kích thước 2x2x3 từ danh sách [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]].


In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [21]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6], [1, 2]])
print(arr_2d)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [15]:
arr_3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]

])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
#Xác định lỗi và sửa lỗi trong code sau
arr_3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ],
    [
        [7, 8, 9]
    ]

])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## Bài tập 2: Initial Placeholders
* Khởi tạo một mảng 2D kích thước 3x4 với tất cả các phần tử là 0 bằng phương thức zeros()

* Khởi tạo một mảng 2D kích thước 3x4 với tất cả các phần tử là 1 bằng phương thức ones()

* Khởi tạo một mảng 1D có giá trị từ 1 đến 10 bằng phương thức arange()

* Khởi tạo một mảng 3D kích thước 2x3x2 với tất cả các phần tử là 7 bằng phương thức full()

* Khởi tạo một ma trận đơn vị (identity matrix) kích thước 4x4 bằng phương thức eye()

* Khởi tạo một mảng 2D kích thước 3x3 với các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 bằng phương thức random.random()


### 1. Khởi tạo một mảng 2D kích thước 3x4 với tất cả các phần tử là 0 bằng phương thức zeros()


In [35]:
import numpy as np

arr_zeros = np.zeros((3, 4), dtype=float)
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
arr_zeros = np.zeros(3, dtype=int)
print(arr_zeros)

[0 0 0]


### 2. Khởi tạo một mảng 2D kích thước 3x4 với tất cả các phần tử là 1 bằng phương thức ones()


In [1]:
import numpy as np

arr_ones = np.ones((3, 4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 3. Khởi tạo một mảng 1D có giá trị từ 1 đến 10 bằng phương thức arange()

In [50]:
import numpy as np

arr_arange = np.arange(2, 4, 0.5)
print(arr_arange)

[2.  2.5 3.  3.5]


In [61]:
timearray = np.arange('2023-06-13', '2023-06-30',np.timedelta64(1, 'D'), dtype='datetime64')
print(timearray)


['2023-06-13' '2023-06-14' '2023-06-15' '2023-06-16' '2023-06-17'
 '2023-06-18' '2023-06-19' '2023-06-20' '2023-06-21' '2023-06-22'
 '2023-06-23' '2023-06-24' '2023-06-25' '2023-06-26' '2023-06-27'
 '2023-06-28' '2023-06-29']


### 4. Khởi tạo một mảng 3D kích thước 2x3x2 với tất cả các phần tử là 7 bằng phương thức full()

In [69]:
import numpy as np

arr_full = np.full((2, 3, 2), 7)
print(arr_full)

[[[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]]


In [70]:
arr_full_like = np.full_like(arr_full, 9)
print(arr_full_like)

[[[9 9]
  [9 9]
  [9 9]]

 [[9 9]
  [9 9]
  [9 9]]]


### 5. Khởi tạo một ma trận đơn vị (identity matrix) kích thước 4x4 bằng phương thức eye()

In [74]:
arr_eye = np.eye(4)
print(arr_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 6. Khởi tạo một mảng 2D kích thước 3x3 với các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 bằng phương thức random.random()

In [79]:
import numpy as np

arr_random = np.random.random(size=(3, 3))
print(arr_random)

[[0.42594886 0.86780846 0.9891014 ]
 [0.84165248 0.89497334 0.44454127]
 [0.90359351 0.83122143 0.13788015]]


## Important Function

### Bài 1: Cho một mảng NumPy arr = np.array([1, 5, 8, 10, 3, 6]). Hãy cắt giới hạn các giá trị trong mảng vào khoảng từ 3 đến 8.


In [ ]:
import numpy as np

arr1 = np.array([1, 5, 8, 10, 3, 6])
clipped_arr1 = np.clip(arr1, 3, 8)
print(clipped_arr1)

### Bài 2: Cho hai mảng NumPy arr1 = np.array([1, 2, 3]) và arr2 = np.array([4, 5, 6]). Hãy nối các mảng lại thành một mảng mới theo chiều ngang.


In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr1 = np.concatenate((arr1, arr2))
print(concatenated_arr1)

[1 2 3 4 5 6]


### Bài 3: Cho một mảng NumPy arr = np.array([1, 2, 3, 4, 5]). Hãy thêm một trục mới vào mảng.


In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
new_arr1 = arr1[:, np.newaxis]
print(new_arr1)

[[1]
 [2]
 [3]
 [4]
 [5]]


### Bài 4: Viết một hàm calculate_circle_area(radius) nhận đầu vào là một mảng radius và trả về một mảng chứa diện tích các hình tròn tương ứng. Sử dụng hàm vectorize để tạo một phiên bản vectorized của hàm này và áp dụng nó cho một mảng radius_values chứa các bán kính [1, 2, 3, 4].


In [7]:
import numpy as np

def calculate_circle_area(radius):
    return np.pi * radius**2

# Tạo phiên bản vectorize của hàm calculate_circle_area
vectorized_calculate_circle_area = np.vectorize(calculate_circle_area)

radius_values = np.array([1, 2, 3, 4])
area_values = vectorized_calculate_circle_area(radius_values)

print(area_values)


[ 3.14159265 12.56637061 28.27433388 50.26548246]


### Bài 5: Cho một mảng NumPy arr = np.array([1, 2, 3, 4, 5]). Sử dụng hàm where để tạo một mảng mới new_arr, trong đó các phần tử lớn hơn 3 được thay bằng 0 và các phần tử nhỏ hơn hoặc bằng 3 giữ nguyên giá trị.


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = np.where(arr > 3, 0, arr)

print(new_arr)

[1 2 3 0 0]


### Bài 6: Cho một mảng hai chiều arr = np.array([[1, 2, 3], [4, 5, 6]]). Sử dụng hàm flatten để biến đổi mảng này thành một mảng một chiều.


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()

print(flattened_arr)


[1 2 3 4 5 6]


### Bài 7: Cho một mảng một chiều arr = np.array([1, 2, 3, 4, 5, 6]). Sử dụng hàm reshape để biến đổi mảng này thành một mảng hai chiều có hình dạng (2, 3).


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))

print(reshaped_arr)


[[1 2 3]
 [4 5 6]]
