In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
height, width, channel = img.shape
print(height, width, channel)
print(img.dtype)

cv2.imwrite('output.jpg', img)

400 650 3
uint8


True

### Increate brightness

In [2]:
data = np.array([-4, 3, 8, 300, 7])
print(data)

data = np.clip(data, 0, 255)
print(data)

[ -4   3   8 300   7]
[  0   3   8 255   7]


#### Cách 1

In [19]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

h, w, c = img.shape
for i in range(h):
    for j in range(w):
        for k in range(c):
            img[i, j, k] = img[i, j, k] + 50
            if img[i, j, k] <0:
                img[i, j, k] = 0
            elif img[i, j, k] >255:
                img[i, j, k] = 255
                
img = img.astype('uint8')
cv2.imwrite('increase50_loop.jpg', img)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Cách 2

In [18]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img + 50
img = np.clip(img, 0, 255)

img = img.astype(np.uint8)
cv2.imwrite('increase50_clip.jpg', img)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Cách 3

In [19]:
data = np.array([-4., 3, 8, 300, 7])
print(data)
print(data.dtype)

data = np.where(data<0, 0, data)
print(data)

data = np.where(data>255, 255, data)
print(data)

[ -4.   3.   8. 300.   7.]
float64
[  0.   3.   8. 300.   7.]
[  0.   3.   8. 255.   7.]


In [23]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img + 50
img = np.where(img<0., 0., img)
img = np.where(img>255., 255., img)

img = img.astype(np.uint8)
cv2.imwrite('increase50_where.jpg', img)

True

### Decrease brightness

#### Cách 1

In [27]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

h, w, c = img.shape
for i in range(h):
    for j in range(w):
        for k in range(c):
            img[i, j, k] = img[i, j, k] -80
            if img[i, j, k] <0:
                img[i, j, k] = 0
            elif img[i, j, k] >255:
                img[i, j, k] = 255
                
img = img.astype('uint8')
cv2.imwrite('decrease80_loop.jpg', img)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Cách 2

In [28]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img - 80
img = np.clip(img, 0, 255)

img = img.astype(np.uint8)
cv2.imwrite('decrease80_clip.jpg', img)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Cách 3

In [25]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('nature.jpg', 1)
img = img.astype(float)

img = img - 80
img = np.where(img<0., 0., img)
img = np.where(img>255., 255., img)

img = img.astype(np.uint8)
cv2.imwrite('decrease80_where.jpg', img)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Flipping

In [31]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Đọc ảnh gốc
img = cv2.imread('nature.jpg', 1)

# Chuyển đổi kiểu dữ liệu của ảnh sang kiểu float
img = img.astype(float)

# Lấy kích thước (chiều cao, chiều rộng, độ sâu) của ảnh
height, width, depth = img.shape

# Ma trận biến đổi (xoay ngược theo trục y)
transform = np.array([[1, 0],
                      [0, -1]])

# Khởi tạo ảnh đầu ra với kích thước tương tự ảnh gốc
output = np.zeros((height, width, depth))

# Duyệt qua từng pixel trong ảnh gốc
for i in range(height):
    for j in range(width):
        # Lấy giá trị pixel tại vị trí (i, j)
        pixel = img[i, j, :]

        # Áp dụng ma trận biến đổi để tính toán vị trí mới
        new_j, new_i = transform.dot(np.array([j, i])) + [0, height-1]

        # Gán giá trị pixel vào vị trí mới trong ảnh đầu ra
        output[new_i, new_j, :] = pixel

# Chuyển đổi kiểu dữ liệu của ảnh đầu ra sang kiểu uint8
output = output.astype(np.uint8)

# Lưu ảnh đầu ra thành file
cv2.imwrite('flipping_x.jpg', output)

# Hiển thị ảnh đầu ra
cv2.imshow("img", output)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Đọc ảnh gốc
img = cv2.imread('nature.jpg', 1)

# Chuyển đổi kiểu dữ liệu của ảnh sang kiểu float
img = img.astype(float)

# Lấy kích thước (chiều cao, chiều rộng, độ sâu) của ảnh
height, width, depth = img.shape

# Ma trận biến đổi (xoay ngược theo trục y)
transform = np.array([[-1, 0],
                      [0, 1]])

# Khởi tạo ảnh đầu ra với kích thước tương tự ảnh gốc
output = np.zeros((height, width, depth))

# Duyệt qua từng pixel trong ảnh gốc
for i in range(height):
    for j in range(width):
        # Lấy giá trị pixel tại vị trí (i, j)
        pixel = img[i, j, :]

        # Áp dụng ma trận biến đổi để tính toán vị trí mới
        new_j, new_i = transform.dot(np.array([j, i])) + [width-1, 0]

        # Gán giá trị pixel vào vị trí mới trong ảnh đầu ra
        output[new_i, new_j, :] = pixel

# Chuyển đổi kiểu dữ liệu của ảnh đầu ra sang kiểu uint8
output = output.astype(np.uint8)

# Lưu ảnh đầu ra thành file
cv2.imwrite('flipping_y.jpg', output)

# Hiển thị ảnh đầu ra
cv2.imshow("img", output)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Convert to grayscale

#### Cách 1

In [45]:
import cv2
import numpy as np

img = cv2.imread('nature.jpg', 1)
transform = np.array([0.072, 0.213, 0.715])

height, width, depth = img.shape
output = np.zeros((height, width, depth))
for i in range(height):
    for j in range(width):
        for k in range(depth):
            output[i, j] += img[i, j, k] * transform[k]
output = output.astype('uint8')
cv2.imwrite('nature_grayscale_loop.jpg', output)
cv2.imshow("img", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Cách 2

In [42]:
import cv2
import numpy as np

img = cv2.imread('nature.jpg', 1)
transform = np.array([0.072, 0.213, 0.715])

output = (img@transform).astype("uint8")
cv2.imwrite('nature_grayscale_1.jpg', output)
cv2.imshow("img", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
output.shape

(400, 650)

#### Cách 3

In [39]:
import cv2
import numpy as np

img = cv2.imread('nature.jpg', 1)
transform = np.array([0.072, 0.213, 0.715])

output = img.dot(transform).astype("uint8")
cv2.imwrite('nature_grayscale_2.jpg', output)
cv2.imshow("img", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Background substraction

In [3]:
fake_background = cv2.imread("colorfull-2.jpg")
fake_background = cv2.resize(fake_background, (600, 400))
cv2.imshow("fake background", fake_background)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img1 = cv2.imread('maxresdefault.jpg')
img1 = cv2.resize(img1, (600, 400))

background = cv2.imread('background.jpg')
background = cv2.resize(background, (600, 400))

cv2.imshow("img1", img1)
cv2.imshow("img2", background)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:
diff = np.subtract(img1, background)
cv2.imshow("diff", diff)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("substraction_bg.jpg", diff)

True

In [132]:
diff[0, :, :]

array([[  2, 253,   7],
       [  7,   7,  12],
       [  7,   9,  11],
       ...,
       [  5,   9,   9],
       [  5,   8,   9],
       [  4,   4,   8]], dtype=uint8)

In [10]:
height, width, depth = img1.shape
output = np.zeros((height, width, depth))
for i in range(height):
    for j in range(width):
        for k in range(depth):
            if diff[i, j, k] <100:
                output[i, j, k] = fake_background[i, j, k]
            else:
                output[i, j, k] = img1[i, j, k]

In [11]:
output = output.astype('uint8')
cv2.imshow("output", output)

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("output_sub_bg.jpg", output)

True

In [60]:
# import cv2

# # Tạo đối tượng VideoCapture để đọc video từ camera
# cap = cv2.VideoCapture(0)  # Số 0 thể hiện camera mặc định, nếu có nhiều camera, hãy chọn số thích hợp.

# # Kiểm tra xem camera có mở thành công hay không
# if not cap.isOpened():
#     print("Không thể mở camera.")
#     exit()

# # Đọc khung hình từ camera
# ret, frame = cap.read()

# # Kiểm tra xem việc đọc khung hình có thành công hay không
# if not ret:
#     print("Không thể đọc khung hình.")
#     exit()

# # Lưu khung hình thành tệp tin hình ảnh
# cv2.imwrite('captured_image.jpg', frame)

# # Hiển thị thông báo lưu thành công
# print("Đã lưu hình ảnh thành công.")

# # Giải phóng tài nguyên
# cap.release()
# cv2.destroyAllWindows()


Đã lưu hình ảnh thành công.


In [58]:
# # Tạo đối tượng VideoCapture để đọc video từ camera
# cap = cv2.VideoCapture(0)  # Số 0 thể hiện camera mặc định, nếu có nhiều camera, hãy chọn số thích hợp.

# # Kiểm tra xem camera có mở thành công hay không
# if not cap.isOpened():
#     print("Không thể mở camera.")
#     exit()

# # Vòng lặp để đọc từng khung hình từ camera
# while True:
#     # Đọc khung hình từ camera
#     ret, frame = cap.read()

#     # Kiểm tra xem việc đọc khung hình có thành công hay không
#     if not ret:
#         print("Không thể đọc khung hình.")
#         break
    
#     # Hiển thị khung hình
#     cv2.imshow('Camera', frame)

#     # Thoát vòng lặp nếu nhấn phím 'q'
#     if cv2.waitKey(1) == ord('q'):
#         break

# # Giải phóng tài nguyên
# cap.release()
# cv2.destroyAllWindows()